### ISSUE TITLE
 Failed to run initializer of com.raicuparta.uuvr problem

### ISSUE THREAD

**Issue by Akeminyaka** [Raicuparta/uuvr#34]
I try to patch game using uuvr[il2cpp ver.] and idk how to fix that:

[Error  :AssemblyPatcher] Failed to run initializer of com.raicuparta.uuvr: System.NullReferenceException: Object reference not set to an instance of an object.
   at AssetsTools.NET.Extra.AssetHelper.FindAssetClassByID(ClassDatabaseFile cldb, UInt32 id)
   at AssetsTools.NET.Extra.AssetsManager.GetTemplateBaseField(AssetsFile file, AssetFileInfoEx info, Boolean forceFromCldb)
   at AssetsTools.NET.Extra.AssetsManager.GetTypeInstance(AssetsFile file, AssetFileInfoEx info, Boolean forceFromCldb)
   at AssetsTools.NET.Extra.AssetsManager.GetATI(AssetsFile file, AssetFileInfoEx info, Boolean forceFromCldb)
   at Patcher.PatchVR(String globalSettingsBackupPath, String globalSettingsFilePath, String classDataPath)
   at Patcher.Initialize()
   at BepInEx.Preloader.Core.Patching.AssemblyPatcher.PatchAndLoad() in /home/runner/work/BepInEx/BepInEx/BepInEx.Preloader.Core/Patching/AssemblyPatcher.cs:line 314

**Comment by Akeminyaka** [comment]
I randomly fix that problem, idk how
